### ISSUE TITLE
XML parse error when contribution activity overview is enabled on GH profile

### ISSUE THREAD

**Issue by klaeufer** [gkthiruvathukal/cv#4]
This might be caused by invalid GH content.

Traceback (most recent call last):
  File "tools/github-commits.py", line 64, in <module>
    tree = ET.parse('/tmp/some.xml')
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 587, column 37

**Comment by gkthiruvathukal** [comment]
Yes. I observed this, too, when testing with your username.  We will have to investigate.

**Comment by gkthiruvathukal** [comment]
I'm going to close this one for now. I think it is resolved by recent fixes.
